### ISSUE TITLE
Is there a way to target a variables.yml in a specific branch?

### ISSUE THREAD

**Issue by mattcowen** [lindluni/actions-variable-groups#1]
is there a way to specify the branch where the variable file is using the repo url? Currently it defaults to main.

**Comment by lindluni** [comment]
I could easily add the ability to specify a branch/tag/sha at the end of the file and parse that ref off of it. Let me take a quick look at it, something like this: `path/to/file@<ref>` where ref is the branch/tag/sha

**Comment by lindluni** [comment]
And if no ref is specified fallback to the default branch

**Comment by lindluni** [comment]
@mattcowen https://github.com/lindluni/actions-variable-groups/pull/2/files

I released it as `v2.0.0`

**Comment by mattcowen** [comment]
good job, works perfectly
