### ISSUE TITLE
Error: Fail to retrieve files ci_environment.yml: Not Found

### ISSUE THREAD

**Issue by dreagor** [lindluni/actions-variable-groups#3]
Hi Brett!

I have a private org and have 2 repos in there, variableGroups and scheduleTask, and I am not able to get the variable group, in variableGroups repo I only have that single File, no typos I am 100% sure

since both repos are in same org I assume there is no need for token (PAT?)

error message
```
Run lindluni/actions-variable-groups@main
  
Processing group ci_environment.yml@master
Retrieving files for group ci_environment.yml
Error: Fail to retrieve files ci_environment.yml: Not Found
```

this is the step I have in the workflow
```
      - uses: lindluni/actions-variable-groups@main
        with:
          org: myOrg #is private :(
          repo: variableGroups
          groups: ci_environment.yml@master
```

**Comment by lindluni** [comment]
Hi @dreagor 

Unfortunately, unless the repo is public, you do need to provide a token. You can use either a Personal Access Token, or you can create a GitHub App with `content: read` scope, install it in your org, and add your repos to the app. Then you can use an Action like the following to generate an App token at runtime to pass on to the `actions-variable-groups` Action: https://github.com/marketplace/actions/action-github-app-token

The benefit of using an App is that the tokens are short-lived, and they are owned by the org, not by a single user.

**Comment by dreagor** [comment]
Thanks a lot!
