### ISSUE TITLE
Can't find variable yml file in V 2.5.0

### ISSUE THREAD

**Issue by Anoop-P-Hegde** [lindluni/actions-variable-groups#8]
We have two repositories such as reusable workflow actions which is called workflow, and another repository is the end user which is
caller workflow.
**We have used  lindluni/actions-variable-groups@v2.5.0 latest 2.5.0 version in our workflows and facing below issue where variable.yml is unable to identify the path.**

**we have placed under .github/variables/<env>/variables.yml**

<img width="488" alt="image" src="https://github.com/user-attachments/assets/c0e1ec98-80d7-47fb-8de4-bfa7a65a9e1e">

Could you please help in resolving this issue. 

**Note: Please treat this issue at highest priority.**

**Comment by Anoop-P-Hegde** [comment]
> We have two repositories such as reusable workflow actions which is called workflow, and another repository is the end user which is caller workflow. **We have used lindluni/actions-variable-groups@v2.5.0 latest 2.5.0 version in our workflows and facing below issue where variable.yml is unable to identify the path.**
> 
> **we have placed under .github/variables//variables.yml**
> 
> <img alt="image" width="488" src="https://private-user-images.githubusercontent.com/138579446/356092453-c0e1ec98-80d7-47fb-8de4-bfa7a65a9e1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDYxMDMsIm5iZiI6MTcyNDA0NTgwMywicGF0aCI6Ii8xMzg1Nzk0NDYvMzU2MDkyNDUzLWMwZTFlYzk4LTgwZDctNDdmYi04ZGU0LWJmYTdhNjVhOWUxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwNTM2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDVlOWVkNDhkYzIyNDYzOGYzMTgyMDU2OTU5NGFiNGI1YzdmM2VhZTExNWNkZTAwNmNlMTVjOTgxYzRhNWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KSO4XCk47fMPF8rXIcxpGb7FEKRYbcAM7K_3Uyc6Fbg">
> Could you please help in resolving this issue.
> 
> **Note: Please treat this issue at highest priority.**

Can anyone please provide a resolution to this issue

**Comment by lindluni** [comment]
It looks like a simple bug, I missed passing the `ref` into the call to retrieve the file list here: https://github.com/lindluni/actions-variable-groups/blob/a09ab106947f24ac43c42b303738eb90977cf714/index.js#L41

I’ll publish a v2.5.1 to address this in the morning.

Thank you for the report!

**Comment by Anoop-P-Hegde** [comment]
> It looks like a simple bug, I missed passing the `ref` into the call to retrieve the file list here:
> 
> https://github.com/lindluni/actions-variable-groups/blob/a09ab106947f24ac43c42b303738eb90977cf714/index.js#L41
> 
> I’ll publish a v2.5.1 to address this in the morning.
> 
> Thank you for the report!

Any update on the new deployment fix

**Comment by Anoop-P-Hegde** [comment]
@lindluni  -  Any update on the above fix

**Comment by Anoop-P-Hegde** [comment]
@lindluni   -  Hi Brett , could you please treat this request at highest priority as we are dependent on these actions and currently its impacting our deliverables.

**Comment by lindluni** [comment]
I just published `v3.0.0` or `v3` that should fix this

**Comment by lindluni** [comment]
@Anoop-P-Hegde 

Were you able to confirm if this fixed your issue?

**Comment by Anoop-P-Hegde** [comment]
> @Anoop-P-Hegde
> 
> Were you able to confirm if this fixed your issue?

@lindluni  -  Thanks for the quick turnaround. Let me test in our actual project workflow and confirm.

**Comment by Anoop-P-Hegde** [comment]
@lindluni  -  I tried using v3.0.0 in our workflow and still facing the same issue. Below is the screenshot attached for reference.

<img width="635" alt="image" src="https://github.com/user-attachments/assets/e6b50985-4473-4d97-a905-985c29d79ee3">


Could you please suggest some workaround for the above outstanding issue.?

**Comment by Anoop-P-Hegde** [comment]
@lindluni   -   Is it feasible to have some teams call/ troubleshooting session  in order to fix this problem'
